name = "landingforge-site-deployer"
main = "src/index.js"
compatibility_date = "2024-09-01"


account_id = "4b414c2bbcf02a3f832f1727420bcef3"

routes = [
  { pattern = "*.landingforge.app/*", zone_name = "landingforge.app" }
]

[[kv_namespaces]]
binding = "HOSTMAP"
id = "4971568854964c02877cfd17ea356680"

[[r2_buckets]]
binding = "SITES_BUCKET"
bucket_name = "landingforge"


